# Import Pandas & CSVs - Create Copies

In [ ]:
import pandas as pd

products = 'https://drive.google.com/file/d/1_56ouLZVXT4oQaDR45ww6sUDcjdf3Cj6/view?usp=drive_link'

def import_csv(url):
    path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
    return pd.read_csv(path)

products_cl = import_csv(products)

In [ ]:
products_cl_copy = products_cl.copy()

# Explore Products Table

In [ ]:
products_cl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10009 entries, 0 to 10008
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          10009 non-null  object
 1   name         10009 non-null  object
 2   desc         10009 non-null  object
 3   price        10009 non-null  float64
 4   promo_price  759 non-null    float64
 5   in_stock     10009 non-null  int64
 6   type         9963 non-null   object
dtypes: float64(2), int64(1), object(4)
memory usage: 547.5+ KB

In [ ]:
products_cl["type"].sample(10)

6812        1298
1298    12635403
4201    5,49E+11
9301    51861714
8664    12175397
145     57445397
6582    1,44E+11
489         5384
5293    11865403
9739    11865403
Name: type, dtype: object

In [ ]:
products_cl["type"].value_counts()

type
11865403     1069
12175397      938
1298          783
11935397      561
11905404      455
             ...
5185            1
5,45E+15        1
51912158        1
113464259       1
12282           1
Name: count, Length: 125, dtype: int64

# Product Categories

## Create category columns

In [ ]:
products_cl_copy["main_category"]=""
products_cl_copy["sub_category"]=""

## Check for 30 largest types

In [ ]:
products_cl_copy["type"].value_counts().nlargest(30)

type
11865403    1069
12175397     938
1298         783
11935397     561
11905404     455
1282         372
12635403     363
13835403     269
5,74E+15     247
1364         216
12585395     190
1296         187
1325         183
5384         177
1433         171
12215397     170
5398         159
1,02E+12     130
57445397     129
1,44E+11     129
1334         115
2449         107
2158         107
12655397     105
1229         104
12995397      95
1515          88
13615399      78
13555403      75
1405          75
Name: count, dtype: int64

In [ ]:
#products_cl_copy.loc[products_cl["type"]=="11865403"]
products_cl_copy.loc[products_cl_copy["name"].str.contains("second hand", case=False)]

,sku,name,desc,price,promo_price,in_stock,type,main_category,sub_category
1173,AP20102,Second hand - Apple iPad Smart Cover Case Air ...,Leather Case for iPad Air used (like new),45.00,NaN,0,12635403,,
2968,AP20104,Second hand - Apple iPad Case Silicone Case Mi...,used protective case ultrafine silicone cases ...,69.00,NaN,0,12635403,,
4063,AP20110,Second hand - Apple iPad Silicone Case Pro 97 ...,Silicone light cover and soft touch for iPad P...,79.00,NaN,0,12635403,,
4065,AP20109,Second hand - Apple iPad Silicone Case Pro 97 ...,Case silicone used light and soft touch for iP...,79.00,NaN,0,12635403,,
6193,PAC1914,"Second hand - Apple iMac 20 ""Core 2 Duo 24GHz ...",IMac used 20 inch Core 2 Duo 24GHz | 2GB RAM |...,309.99,NaN,0,1282,,
...,...,...,...,...,...,...,...,...,...
8735,PAC2282,"Second hand - Apple iMac 20 ""Core 2 Duo 226GHz...",Refurbished iMac 20 inch Core 2 Duo | 2GB RAM ...,1199.00,NaN,0,"5,43E+15",,
8736,PAC2281,"Second hand - Apple iMac 20 ""Core 2 Duo 226GHz...",Refurbished iMac 20 inch Core 2 Duo | 2GB RAM ...,1499.00,NaN,0,"5,43E+15",,
8737,PAC2285,Second hand - Apple Mac mini Core 2 Duo 24GHz ...,Computer Refurbished Mac mini Core 2 Duo | 4GB...,699.00,NaN,0,"5,45E+15",,
9279,AP20443,Second hand - Apple Leather Case leather case ...,ultrathin leather case and microfiber premium ...,55.00,NaN,0,11865403,,
9610,PAC2286,"Second hand - Apple LED Cinema Display 24 """,Monitor Refurbished Apple Cinema Display 24 inch,899.00,499.0,0,1282,,

## Create categories

### Created categories based on type

In [ ]:
# Function to create main- and sub-category
def create_type_category(type,m_category,s_category):
  for index, row in products_cl_copy.iterrows():
    if row["type"] == type:
        if m_category not in row["main_category"]:
          if row["main_category"] == "":
              products_cl_copy.loc[index, "main_category"] += m_category
          else:
              products_cl_copy.loc[index, "main_category"] += ", " + m_category
        if s_category not in row["sub_category"]:
            if row["sub_category"] == "":
              products_cl_copy.loc[index, "sub_category"] += s_category
            else:
              products_cl_copy.loc[index, "sub_category"] += ", " + s_category

In [ ]:
create_type_category("11865403","case","iphone_case")
create_type_category("12175397","server","server")
create_type_category("11935397","storage","external_storage")
create_type_category("1298","","open")
create_type_category("11905404","wireless","wirless_device")
create_type_category("1282","workstation","workstation")
create_type_category("12635403","case","ipad_case")
create_type_category("13835403","case","macbook_case")
create_type_category("5,74E+15","workstation","imac")
create_type_category("1364","pc_components","memory")
create_type_category("12585395","peripherie","usb_devices")
create_type_category("1296","monitor","monitor")
create_type_category("1325","cable","cable")
create_type_category("5384","peripherie","headphones")
create_type_category("1433","storage","ssd_expansion_kit")
create_type_category("12215397","storage","ssd_storage")
create_type_category("5398","peripherie","speaker")
create_type_category("1,02E+12","workstation","macbook_pro")
create_type_category("57445397","storage","portable_storage")
create_type_category("1,44E+11","repair","repair")
create_type_category("1334","peripherie","network_devices")
create_type_category("2449","smartphone","wearables")
create_type_category("2158","workstation","macbook_pro")
create_type_category("12655397","storage","internal_storage")
create_type_category("1229","peripherie","pen")
create_type_category("12995397","peripherie","pc_expansion")
create_type_category("1515","peripherie","battery")
create_type_category("13615399","peripherie","charger")
create_type_category("13555403","smartphone","screen_protector")
create_type_category("1405","tablet","graphics_tablet")

In [ ]:
print(products_cl_copy["main_category"].value_counts())
print(products_cl_copy["sub_category"].value_counts())

main_category
                 2945
case             1701
storage          1136
peripherie       1006
server            938
workstation       856
wireless          455
pc_components     216
monitor           187
cable             183
smartphone        182
repair            129
tablet             75
Name: count, dtype: int64
sub_category
                     2162
iphone_case          1069
server                938
open                  783
external_storage      561
wirless_device        455
workstation           372
ipad_case             363
macbook_case          269
imac                  247
macbook_pro           237
memory                216
usb_devices           190
monitor               187
cable                 183
headphones            177
ssd_expansion_kit     171
ssd_storage           170
speaker               159
repair                129
portable_storage      129
network_devices       115
wearables             107
internal_storage      105
pen                   104
pc_expansion           95
battery                88
charger                78
screen_protector       75
graphics_tablet        75
Name: count, dtype: int64

### Created categories based on words

In [ ]:
import re

# check for smartphones
for index, row in products_cl_copy.iterrows():
    if (re.search(r"^.{0,7}apple iphone", row["name"], re.IGNORECASE) and (row["price"] > 200)):
        if "smartphone" not in row["main_category"]:
          if row["main_category"] == "":
              products_cl_copy.loc[index, "main_category"] += "smartphone"
        if "smartphone" not in row["sub_category"]:
          if row["sub_category"] == "":
              products_cl_copy.loc[index, "sub_category"] += "smartphone"
          else:
              products_cl_copy.loc[index, "sub_category"] += ", smartphone"

# check for open products
for index, row in products_cl_copy.iterrows():
    if (re.search(r"Open -", row["name"], re.IGNORECASE)
        or re.search(r"Like new -", row["name"], re.IGNORECASE)
        or re.search(r"second hand", row["name"], re.IGNORECASE)
        or re.search(r"reconditioned", row["desc"], re.IGNORECASE)
        or re.search(r"refurbished", row["desc"], re.IGNORECASE)
        or re.search(r"without box", row["desc"], re.IGNORECASE)):
            categories = row["sub_category"].split(", ")  # Split the category string into a list
            if "open" not in categories:  # Check if "open" is already in the list
                if row["sub_category"] == "":
                    products_cl_copy.loc[index, "sub_category"] = "open"
                else:
                    products_cl_copy.loc[index, "sub_category"] += ", open"

# check for battery
for index, row in products_cl_copy.iterrows():
    if (re.search(r"battery", row["desc"], re.IGNORECASE)):
        if "peripherie" not in row["main_category"]:
          if row["main_category"] == "":
              products_cl_copy.loc[index, "main_category"] += "peripherie"
        if "battery" not in row["sub_category"]:
          if row["sub_category"] == "":
              products_cl_copy.loc[index, "sub_category"] += "battery"
          else:
              products_cl_copy.loc[index, "sub_category"] += ", battery"

# check for ipad
for index, row in products_cl_copy.iterrows():
    if (re.search(r"ipad", row["desc"], re.IGNORECASE)) and (row["price"] > 300):
        if "tablet" not in row["main_category"]:
          if row["main_category"] == "":
              products_cl_copy.loc[index, "main_category"] += "tablet"
        if "ipad" not in row["sub_category"]:
          if row["sub_category"] == "":
              products_cl_copy.loc[index, "sub_category"] += "ipad"
          else:
              products_cl_copy.loc[index, "sub_category"] += ", ipad"

#check for keyboard and mouse
# check for open products
for index, row in products_cl_copy.iterrows():
    if (re.search(r"keyboard", row["name"], re.IGNORECASE)
        or re.search(r"mouse", row["name"], re.IGNORECASE)
        or re.search(r"keyboard", row["desc"], re.IGNORECASE)
        or re.search(r"mouse", row["desc"], re.IGNORECASE)):
            categories = row["main_category"].split(", ")  # Split the category string into a list
            if "peripherie" not in categories:  # Check if "peripherie" is already in the list
                if row["main_category"] == "":
                    products_cl_copy.loc[index, "main_category"] = "peripherie"
            categories = row["sub_category"].split(", ")  # Split the category string into a list
            if "input_devices" not in categories:  # Check if "input_devices" is already in the list
                if row["sub_category"] == "":
                    products_cl_copy.loc[index, "sub_category"] = "input_devices"
                else:
                    products_cl_copy.loc[index, "sub_category"] += ", input_devices"

In [ ]:
print(products_cl_copy["main_category"].value_counts())
print(products_cl_copy["sub_category"].value_counts().head(35))

main_category
                 2351
case             1701
peripherie       1255
storage          1136
server            938
workstation       856
wireless          455
smartphone        332
tablet            270
pc_components     216
monitor           187
cable             183
repair            129
Name: count, dtype: int64
sub_category
                     1354
open                  997
iphone_case           994
server                920
external_storage      516
wirless_device        413
ipad_case             320
workstation           309
macbook_case          256
imac                  233
macbook_pro           216
memory                214
battery               193
ssd_expansion_kit     170
cable                 167
usb_devices           160
monitor               157
ssd_storage           156
headphones            145
ipad                  141
repair                128
portable_storage      125
speaker               119
smartphone            105
network_devices       105
wearables             101
pen                    89
internal_storage       88
pc_expansion           88
screen_protector       74
input_devices          74
charger                69
graphics_tablet        67
iphone_case, open      64
open, ipad             54
Name: count, dtype: int64

In [ ]:
#set the rest of products to other
for index, row in products_cl_copy.iterrows():
          if row["main_category"] == "":
              products_cl_copy.loc[index, "main_category"] += "other"
          if row["sub_category"] == "":
              products_cl_copy.loc[index, "sub_category"] += "other"
          if row["sub_category"] == "open":
              products_cl_copy.loc[index, "sub_category"] += ", other"

In [ ]:
print(products_cl_copy["main_category"].value_counts())
print(products_cl_copy["sub_category"].value_counts().head(35))

main_category
other            2351
case             1701
peripherie       1255
storage          1136
server            938
workstation       856
wireless          455
smartphone        332
tablet            270
pc_components     216
monitor           187
cable             183
repair            129
Name: count, dtype: int64
sub_category
other                1354
open, other           997
iphone_case           994
server                920
external_storage      516
wirless_device        413
ipad_case             320
workstation           309
macbook_case          256
imac                  233
macbook_pro           216
memory                214
battery               193
ssd_expansion_kit     170
cable                 167
usb_devices           160
monitor               157
ssd_storage           156
headphones            145
ipad                  141
repair                128
portable_storage      125
speaker               119
smartphone            105
network_devices       105
wearables             101
pen                    89
internal_storage       88
pc_expansion           88
screen_protector       74
input_devices          74
charger                69
graphics_tablet        67
iphone_case, open      64
open, ipad             54
Name: count, dtype: int64

## Save Products Table

In [ ]:
from google.colab import files

products_cl_copy.to_csv("products_qu.csv", index=False)
files.download("products_qu.csv")